### ISSUE TITLE
Question about the initial LOCATION_CHANGE events.

### ISSUE THREAD

**Issue by sorahn** [reactjs/react-router-redux#486] opened 2016-11-24 18:46 UTC
I did some digging to find out about the initial `LOCATION_CHANGE` event.  It seems that in recent releases it was set up to always fire no matter what. 

A problem I'm seeing now is that I'm using url-rewrite rules on the server, and now when the action fires on the initial page load, it loads what the browser has in the URL, not what the server received and rendered.

I did confirm that the `initialState` passed by the server does have the correct location object, and the action is being sent into my reducer as a `POP` action.

I tried to follow all the other discussions about it, but didn't see a good example of how to have it not do that now ( If thats possible ).  I See that there is a `adjustUrlOnReplay` option to set, and I tried setting that to false, but that didn't seem to help.

There was also something said in one of the issues about being required do this to sync the history objects, so if that's the case and there is no way to use the existing location object, and /not/ fire an update then I might be SOL here :(

And if anyone else has a suggestion, here is what I'm trying to acomplish:
```
User URL                    => What NGINX sends to node
$user.domain.com            => domain.com/space/user
domain.com/space/user       => domain.com/space/user
$user.domain.com/some/path  => domain.com/some/path
```

Ideally this allows all of our users to have a subdomain and clicking on the links to `/` just always take them to their space, instead of the home page.  And this moves all of the complexity to 2 lines nginx config, instead of having the application try to parse the url to figure out what to do.

Thanks for your time!

**Comment by ulrik59** [comment] 2016-12-16 09:56
I have the same problem with [react-boilerplate](https://github.com/mxstbr/react-boilerplate). In this boilerplate, sagas ([redux-saga](https://github.com/yelouafi/redux-saga)) are loaded and cancelled dynamically on route change. The problem is the initial `LOCATION_CHANGE` action happen so quickly that the initial sagas, which should be cancelled, are not loaded. This results in duplicated sagas which obviously create a lot of bugs.
The only solution I found for the moment is to lock `react-router-redux` to `4.0.6`.

**Comment by timdorr** [comment] 2017-02-08 17:54
Dupe of #481.

**Closed by timdorr** 2017-02-08 17:54 UTC
